version: '3.8'

services:
  # ──────────────── Airflow Postgres ─────────────────
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ──────────────── Metabase Postgres ────────────────
  metabase-postgres:
    image: postgres:13
    container_name: metabase-postgres
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: metabase
      POSTGRES_PASSWORD: metabase
    volumes:
      - metabase-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U metabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ───────────── AIRFLOW WEBSERVER ─────────────
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./dbt:/opt/airflow/dbt
      - ~/.dbt:/root/.dbt
    ports:
      - "8080:8080"
    command: webserver

  # ───────────── AIRFLOW SCHEDULER ─────────────
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./dbt:/opt/airflow/dbt
      - ~/.dbt:/root/.dbt
    command: scheduler

  # ─────────────── METABASE ────────────────
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    depends_on:
      metabase-postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: metabase-postgres

  # ─────────────── DBT ────────────────
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.7.9
    container_name: dbt
    volumes:
      - ./dbt:/opt/airflow/dbt
      - ~/.dbt:/root/.dbt
    working_dir: /opt/airflow/dbt
    entrypoint: ["tail", "-f", "/dev/null"]

volumes:
  postgres_data:
  metabase-data: